# Generated by Django 4.2 on 2025-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='codigo',
            field=models.CharField(max_length=52, unique=True),
        ),
    ]
