# Generated by Django 4.2 on 2025-05-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_parceiro_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='primeiro_acesso',
        ),
        migrations.AddField(
            model_name='parceiro',
            name='status',
            field=models.CharField(default='Sem registro', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='canais_venda',
            field=models.ManyToManyField(blank=True, to='usuarios.canalvenda'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_user',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor'), ('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='abril',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='agosto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='canal_venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.canalvenda'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='dezembro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='fevereiro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='fevereiro_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='janeiro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='janeiro_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='julho',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='junho',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='maio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='marco',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='marco_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='novembro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='outubro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='parceiro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='recorrencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='setembro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='tm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='total_geral',
            field=models.FloatField(default=0),
        ),
    ]
