# Generated by Django 4.2 on 2025-05-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_primeiro_acesso_parceiro_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiro',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='canais_venda',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.canalvenda'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_user',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GESTOR', 'Gestor'), ('ADMIN', 'Administrador')], default='VENDEDOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='abril',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='agosto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='canal_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros', to='usuarios.canalvenda'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='codigo',
            field=models.CharField(max_length=52, unique=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='dezembro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='fevereiro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='fevereiro_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='janeiro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='janeiro_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='julho',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='junho',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='maio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='marco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='marco_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='novembro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='outubro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='parceiro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='recorrencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='setembro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='tm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='total_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
