# Generated by Django 4.2 on 2025-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_parceiro_status_customuser_primeiro_acesso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_vendedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_user',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor'), ('VENDEDOR', 'Vendedor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='recorrencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
