# Generated by Django 4.2 on 2025-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_customuser_id_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
