# Generated by Django 4.2 on 2025-05-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_parceiro_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('ligacao', 'Ligação')], max_length=20)),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('entrou_em_contato', models.BooleanField(default=False)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='usuarios.parceiro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
