# Generated by Django 4.2 on 2025-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_interacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_user',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GESTOR', 'Gestor'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
