# Generated by Django 4.2 on 2025-05-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_customuser_tipo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('etapa', models.CharField(choices=[('oportunidade', 'Oportunidade'), ('orcamento', 'Orçamento'), ('pedido', 'Pedido'), ('perdida', 'Venda Perdida')], default='oportunidade', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='usuarios.parceiro')),
            ],
        ),
    ]
