# Generated by Django 4.2 on 2025-06-02 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_oportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='usuario',
            field=models.ForeignKey(default=9876, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
