# Generated by Django 4.2 on 2025-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_gatilhoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
