# Generated by Django 4.2 on 2025-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_interacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='data_etapa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
