# Generated by Django 4.2 on 2025-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_oportunidade_data_etapa_oportunidade_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='etapa',
            field=models.CharField(choices=[('oportunidade', 'Oportunidade'), ('orcamento', 'Orçamento'), ('aguardando', 'Aguardando Pagamento'), ('pedido', 'Pedido'), ('perdida', 'Venda Perdida')], default='oportunidade', max_length=20),
        ),
    ]
