# Generated by Django 4.2 on 2025-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_oportunidade_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='gatilho_extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='gatilho_extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
