# Generated by Django 4.2 on 2025-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_interacao_gatilho_extra_oportunidade_gatilho_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='motivo_venda_perdida',
            field=models.CharField(blank=True, choices=[('preco', 'Preço'), ('prazo', 'Prazo de entrega'), ('concorrente', 'Fechou com concorrente'), ('fora_perfil', 'Fora de perfil'), ('nao_respondeu', 'Cliente não respondeu'), ('outro', 'Outro')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='outro_motivo',
            field=models.CharField(blank=True, help_text="Preencher se selecionou 'Outro'", max_length=255, null=True),
        ),
    ]
