# Generated by Django 4.2 on 2025-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_remove_oportunidade_motivo_venda_perdida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='motivo_venda_perdida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo da Venda Perdida'),
        ),
    ]
