# Generated by Django 4.2 on 2025-06-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_oportunidade_motivo_venda_perdida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='primeiro_acesso',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='canais_venda',
            field=models.ManyToManyField(blank=True, to='usuarios.canalvenda'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_user',
            field=models.CharField(max_length=20),
        ),
    ]
