# Generated by Django 4.2 on 2025-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_alter_canalvenda_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
