# Generated by Django 4.2 on 2025-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_oportunidade_numero_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoParceirosMensal',
            fields=[
                ('parceiro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('parceiro', models.CharField(max_length=255)),
                ('consultor', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('status_parceiro', models.CharField(max_length=50)),
                ('data_ref', models.DateField()),
                ('total_interacoes', models.IntegerField()),
                ('interacoes_whatsapp', models.IntegerField()),
                ('interacoes_ligacao', models.IntegerField()),
                ('interacoes_email', models.IntegerField()),
                ('total_oportunidades', models.IntegerField()),
                ('valor_total_oportunidades', models.DecimalField(decimal_places=2, max_digits=14)),
                ('oportunidades_pedido', models.IntegerField()),
                ('oportunidades_perdida', models.IntegerField()),
                ('oportunidades_oportunidade', models.IntegerField()),
                ('oportunidades_orcamento', models.IntegerField()),
                ('oportunidades_aguardando', models.IntegerField()),
            ],
            options={
                'db_table': 'resumo_parceiros_mensal',
                'managed': False,
            },
        ),
    ]
