# Generated by Django 4.2 on 2025-07-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_resumoparceirosmensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='gatilho_extra_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
