# Generated by Django 4.2 on 2025-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_interacao_gatilho_extra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatilhoextra',
            name='gatilho_utilizado',
            field=models.BooleanField(default=False),
        ),
    ]
