# Generated by Django 4.2 on 2025-07-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_gatilhoextra_gatilho_utilizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatilhoextra',
            name='gatilho_utilizado',
        ),
        migrations.RemoveField(
            model_name='interacao',
            name='gatilho_extra_id',
        ),
    ]
