# Generated by Django 4.2 on 2025-07-18 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_gatilhoextra_gatilho_utilizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatilhoextra',
            name='observacao_gatilho',
            field=models.TextField(blank=True, null=True),
        ),
        #migrations.CreateModel(
        #    name='InteracaoGerada',
        #    fields=[
         #       ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
         #       ('status', models.CharField(blank=True, max_length=255, null=True)),
         #       ('data_geracao', models.DateTimeField(auto_now_add=True)),
         #       ('id_vendedor', models.CharField(blank=True, max_length=100, null=True)),
         #       ('canal_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.canalvenda')),
         #       ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geracoes_interacao', to='usuarios.parceiro')),
         #       ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        #    ],
       # ),
    ]
